# Generated by Django 5.1.2 on 2024-10-25 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('fullname', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('web', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='backend.post')),
            ],
        ),
    ]
