# Generated by Django 5.1.2 on 2024-10-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_formapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formapply',
            name='fullname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
